### ISSUE TITLE
Move to JuliaArrays?

### ISSUE THREAD

**Issue by Tokazama** [JuliaArrays/ArrayInterface.jl#125]
This has been brought up several times but most recently here https://discourse.julialang.org/t/converting-between-axisarray-like-packages/. I think it makes sense to move this package to JuliaArrays. I know that @timholy and @rafaqz are in favor.

@chriselrod , @ChrisRackauckas, @DilumAluthge. What do you think?

**Comment by DilumAluthge** [comment]
Sounds good to me!

**Comment by ChrisRackauckas** [comment]
Yeah why not.

**Comment by DilumAluthge** [comment]
Anyone know who the owners of JuliaArrays are?

@timholy Are you an owner? If so, can you add @Tokazama, @chriselrod, @ChrisRackauckas, and myself as members of JuliaArrays?

**Comment by timholy** [comment]
Done. @ChrisRackauckas, you're already a member, so you didn't get an invite.

**Comment by DilumAluthge** [comment]
I've transferred the ArrayInterface.jl repo to the JuliaArrays org.

Here's the PR to update the URL in General: https://github.com/JuliaRegistries/General/pull/31113

**Comment by ChrisRackauckas** [comment]
💥 thanks for handling it.

**Comment by timholy** [comment]
Thanks all!
