### ISSUE TITLE
ArrayInterface 3.1.7 causes `sum` to freeze on array with missings

### ISSUE THREAD

**Issue by cstjean** [JuliaArrays/ArrayInterface.jl#142]
On Julia 1.5.4 (and 1.5.2)

```julia
(@v1.5) pkg> add Feather, ArrayInterface@3.1.7

julia> using ArrayInterface, Feather
[ Info: Precompiling Feather [becb17da-46f6-5d3c-ad1b-1c5fe96bc73c]

julia> U2 = Matrix{Union{Missing, Float32}}(undef, 10, 10);

julia> my_sum(values::AbstractMatrix) = dropdims(sum(values, dims=2), dims=2)
my_sum (generic function with 1 method)

julia> my_sum(U2)
^C^C^C^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C^CSegmentation fault (core dumped)
````

freezes forever. @etpinard (who is coauthor of this MWE, 👍) says that #137 is to blame. Not sure why `Feather` is necessary. @ExpandingMan, does it ring a bell? Importing Feather's dependencies doesn't cause the issue, so it should be an interaction with Feather's code...

**Comment by ExpandingMan** [comment]
That is quite bizarre....

Just to be sure, you are aware that Feather.jl is basically deprecated in favor of the new Arrow.jl right?  Granted you still need Feather.jl to read the old feather format.

**Comment by etpinard** [comment]
To add to the confusion, using Julia 1.6.0, the above MWE works fine.

**Comment by Tokazama** [comment]
Does this happen with other packages that depend on DataFrames.jl

**Comment by etpinard** [comment]
> Does this happen with other packages that depend on DataFrames.jl

Yep, it does look like it:

```jl
(env) pkg> add DataFrames, ArrayInterface@3.1.7

julia> using DataFrames, ArrayInterface

julia> U2 = Matrix{Union{Missing, Float32}}(undef, 10, 10);

julia> my_sum(values::AbstractMatrix) = dropdims(sum(values, dims=2), dims=2)

julia> my_sum(U2)
```

also hangs forever.

**Comment by etpinard** [comment]
Digging deeper, off the latest master, commenting out

https://github.com/JuliaArrays/ArrayInterface.jl/blob/cd6e5d208330b67a4cb4f4100597500db53242d6/src/axes.jl#L126

and/or

https://github.com/JuliaArrays/ArrayInterface.jl/blob/cd6e5d208330b67a4cb4f4100597500db53242d6/src/axes.jl#L127

makes the MWE work.

**Comment by Tokazama** [comment]
That's bizarre b/c `axes` is not overloaded or exported

**Comment by Tokazama** [comment]
I'm testing this out right now and I think it's a compiler problem. I'm seeing "subtype_tuple_varargs" and "subtype_tuple_tail" being called from a "src/subtype.c" and the julia file calling it is in ".compiler/abstractinterpretation.jl".

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DifferentialEquations.jl/issues/740 seems like another casualty of this? It might be best to revert for now?

**Comment by Tokazama** [comment]
I'm fine with changing that line, but it would be nice to know what is going on here. This seems completely random to me, so I'm not sure how to avoid this issue in the future.

**Comment by ChrisRackauckas** [comment]
@jeffbezanson ?

**Comment by glwagner** [comment]
This issue also has caused problems with `Oceananigans.jl` (one of our functions hangs on compilation with `ArrayInterface@3.1.7`. It _seems_ that [restricting `ArrayInterface` to 3.1.6](https://github.com/CliMA/Oceananigans.jl/pull/1621) solves this problem.

**Comment by glwagner** [comment]
Possible related issue: https://github.com/JuliaLang/julia/issues/40457

**Comment by chriselrod** [comment]
```julia
(@v1.6) pkg> st ArrayInterface DataFrames
      Status `~/.julia/environments/v1.6/Project.toml`
  [4fba245c] ArrayInterface v3.1.7
  [a93c6f00] DataFrames v0.21.8

julia> using DataFrames, ArrayInterface

julia> U2 = Matrix{Union{Missing, Float32}}(undef, 10, 10);

julia> my_sum(values::AbstractMatrix) = dropdims(sum(values, dims=2), dims=2)
my_sum (generic function with 1 method)

julia> my_sum(U2)
10-element reshape(::Matrix{Union{Missing, Float32}}, 10) with eltype Union{Missing, Float32}:
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
```

**Comment by glwagner** [comment]
Hmm... so ArrayInterface 3.1.7 requires julia 1.6?

**Comment by chriselrod** [comment]
Oops, missed the second comment already observing that it works on 1.6.

**Comment by chriselrod** [comment]
On 1.5, it works with DataFrames 1:
```julia
julia> @time using ArrayInterface, DataFrames
  2.827163 seconds (6.67 M allocations: 361.754 MiB, 1.69% gc time)

julia> U2 = Matrix{Union{Missing, Float32}}(undef, 10, 10);

julia> my_sum(values::AbstractMatrix) = dropdims(sum(values, dims=2), dims=2)
my_sum (generic function with 1 method)

julia> @time @time my_sum(U2)
  0.357954 seconds (1.32 M allocations: 70.327 MiB, 8.04% gc time)
  0.358070 seconds (1.32 M allocations: 70.329 MiB, 8.04% gc time)
10-element reshape(::Array{Union{Missing, Float32},2}, 10) with eltype Union{Missing, Float32}:
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing

julia> versioninfo()
Julia Version 1.5.4-pre.23
Commit 071ee979be* (2021-03-01 17:39 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```
but with Feather:
```julia
julia> @time @time my_sum(U2)
^C^C^C^C^CWARNING: Force throwing a SIGINT
Internal error: encountered unexpected error in runtime:
InterruptException()
segv_handler at /home/chriselrod/Documents/languages/julia-noshared-lib/src/signals-unix.c:235
^C^C^C^C^C^C^C^C^C^C^C^C^C 20.419901 seconds (182.66 M allocations: 10.668 GiB, 3.72% gc time)
 20.420008 seconds (182.66 M allocations: 10.668 GiB, 3.72% gc time)
10-element reshape(::Array{Union{Missing, Float32},2}, 10) with eltype Union{Missing, Float32}:
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
 missing
```
I ran out of patience after 20 seconds, but then it returned the correct result after ctrl-c.

**Comment by chriselrod** [comment]
As @Tokazama said, `axes` isn't exported
```julia
julia> ArrayInterface.axes === Base.axes
false

julia> ArrayInterface.axes === axes
false
```
So I don't know why it should matter, but #144 fixes the problem for me locally.
I'll merge and tag a release as soon as someone approves/tests to confirm it fixed it for them, too.

**Comment by evetion** [comment]
Downgrading to 3.1.6 fixes `GeoArrays.jl`: [hanging master build](https://github.com/evetion/GeoArrays.jl/runs/2451229563?check_suite_focus=true) vs [fixed downgrade build](https://github.com/evetion/GeoArrays.jl/runs/2451245139). Locally this also fixes `SpaceLiDAR.jl`. 🎉 🎉 🎉

**Comment by evetion** [comment]
Since this affected several packages already in the precompilation stage, it might be good to actually re-release 3.1.7 with the fix. It's a patch version and pinning it in packages that only indirectly depend on it seems quite ugly.

**Comment by chriselrod** [comment]
I'd make a PR to General, but not sure how to get the appropriate [git-tree-sha1](https://github.com/JuliaRegistries/General/blob/4e7d7d7eeb52308a4a43718bbb5c52565c43d004/A/ArrayInterface/Versions.toml#L209). It's not the same as the commit.

**Comment by chriselrod** [comment]
@DilumAluthge thoughts/suggestions?

**Comment by KristofferC** [comment]
You cannot re-release a version, you just tag a new patch version. People upgrade and get it.

**Comment by DilumAluthge** [comment]
After you release 3.1.8, if 3.1.7 is so bad that nobody should ever use it, you can yank it.

But usually just releasing 3.1.8 should be sufficient.
