### ISSUE TITLE
doc links are broken with 404

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaArrays/ArrayInterface.jl#179]
See https://github.com/JuliaArrays/ArrayInterface.jl/stable

**Comment by Tokazama** [comment]
I think that something needs to be changed in the settings for the pages to properly deploy. @DilumAluthge do you have access to change these settings, as you are the guru of Julia's Github actions.

**Comment by DilumAluthge** [comment]
So, when the docs are built, they become available here:
1. https://juliaarrays.github.io/ArrayInterface.jl/dev
2. https://juliaarrays.github.io/ArrayInterface.jl/stable

Note that the `stable` link will only become available after you have registered a new release.

But the `dev` link should be available already. I'm not sure why your pages didn't build. Can you make another commit to master?

**Comment by DilumAluthge** [comment]
Ah. The `dev` link is showing up for me now. Probably a cache issue with GitHub's CDN.

An easy way to bypass the cache is to stick a dummy query parameter at the end of the link. So e.g. if you do this:
- https://juliaarrays.github.io/ArrayInterface.jl/dev?foo=111

That bypasses the cache.

**Comment by DilumAluthge** [comment]
> So, when the docs are built, they become available here:
> 
> 1. https://juliaarrays.github.io/ArrayInterface.jl/dev
> 2. https://juliaarrays.github.io/ArrayInterface.jl/stable

You should probably edit the badges in the README to link to these URLs.

**Comment by Tokazama** [comment]
@xiaodaigh, I'm able to access the dev pages right now. Are things working on your end?

**Comment by chriselrod** [comment]
Dev page works for me, but I do get a 404 for stable.

**Comment by Tokazama** [comment]
I'm not sure why that is but I'm trying to figure it out.

**Comment by xiaodaigh** [comment]
dev is working but not stable.

**Comment by DilumAluthge** [comment]
When TagBot creates a tag, this will not trigger docs to build on your tag unless you have created an SSH keypair, added the public key as a deploy key to this repo (with write access), and added the private key as a GitHub secret named `DOCUMENTER_KEY`.

**Comment by Tokazama** [comment]
Okay. That's what I originally thought was wrong, but I don't have access to the settings for any repos in JuliaArrays.

**Comment by chriselrod** [comment]
> When TagBot creates a tag, this will not trigger docs to build on your tag unless you have created an SSH keypair, added the public key as a deploy key to this repo (with write access), and added the private key as a GitHub secret named `DOCUMENTER_KEY`.

Thanks! I didn't check for them.
I apparently do have access, so I added them.
I'll tag another release.

**Comment by Tokazama** [comment]
Thanks!

**Comment by chriselrod** [comment]
No problem, thanks for doing all the real work. Stable docs work for me now.

**Comment by Tokazama** [comment]
@xiaodaigh, I think this issue is resolved now so I'm closing it. Feel free to open another issue if necessary.
