### ISSUE TITLE
Add is_strided

### ISSUE THREAD

**Issue by oxinabox** [JuliaArrays/ArrayInterface.jl#24]
see https://github.com/JuliaLang/julia/issues/2345#issuecomment-54537633

**Comment by ChrisRackauckas** [comment]
Definitely agree

**Comment by chriselrod** [comment]
I want something that only returns `true` if we can call `pointer` (or `Base.unsafe_convert(Ptr{T}, A)`) and get a `Ptr` to valid CPU memory.
With it returning false for `GPUArrays` (which are `<: StridedArray`), I could use that for `LoopVectorization.check_args`.

**Comment by chriselrod** [comment]
@mbauman, I hope I can ping you here to ask both about implementation, and what you think should be covered.

I would be happy with something like:
```julia
is_strided(::Any) = false
is_strided(::StridedArray) = true
# library support
is_strided(::GPUArrays.GPUArray) = false
is_strided(::StaticArrays.MArray) = true
```
and I can special case support for things like `PermutedDimsArray` of `is_strided` arrays myself.

But it depends upon what interfaces we want `is_strided(A) == true` to promise support for.
What I am suggesting above is:
1. You can get a pointer to memory the `CPU` can work with.
2. The memory is strided and column major.

I'd also like to have something else for whether `isone(LinearAlgebra.stride1(A))` is known to be true at compile time.

**Comment by Tokazama** [comment]
Can we close this now that we have `defines_strides`?
