### ISSUE TITLE
`ArrayInterface.length`?

### ISSUE THREAD

**Issue by nchisholm** [JuliaArrays/ArrayInterface.jl#254]
I decided to try out `ArrayInterface` for a package I am writing and I have found it very useful.

I was surprised to find that there is no `ArrayInterface.length` that is analogous to `ArrayInterface.size`.  For example,
```julia
julia> using ArrayInterface, StaticArrays

julia> A = SMatrix{2,2}(1:4)
2×2 SMatrix{2, 2, Int64, 4} with indices SOneTo(2)×SOneTo(2):
 1  3
 2  4

julia> ArrayInterface.size(A)
(static(2), static(2))

julia> ArrayInterface.length(A)
4
```
I expected last result to be `static(4)` rather than `4` since all the dimensions of `A` are static.  However, it turns out that `ArrayInterface.length === Base.length`.  Why not define something like `ArrayInterface.length(A) = reduce(*, ArrayInterface.size(A))`, which would give `static(4)` in the example above?

One might also have cases where the length of an array is known but the size of one or more of the dimensions is not.  For example, I think the output of `reshape(A, ...)` would usually be like this because the `length` is invariant but the `size` is not.  In fact,
```julia
ArrayInterface.known_length(ArrayInterface.size(reshape(A, :)))
```
returns `nothing` even though it really is known.  Something more sophisticated than my suggestion above would be required to handle this case though.

**Comment by ChrisRackauckas** [comment]
Seems like just a missing part of the interface. Would be good to have.

**Comment by nchisholm** [comment]
Looking at how things are done in `Base`, I think all that is needed is `ArrayInterface.length(A) = prod(ArrayInterface.size(A))` and then users can specify a special `ArrayInterface.length` method if they need.  One could also handle special cases that might be common like
```julia
ArrayInterface.length(R::ReshapedArray{Base.ReshapedArray{Int64, 2, SMatrix{3, 2, Int64, N}}) where N = static(N)
```
However, that might be overkill given that e.g. `Base.reshape` and `Base.PermutedDimsArray` will not propagate / accept static dimensions at present.

**Comment by Tokazama** [comment]
We can just rename and document `ArrayInterface.static_length` to make this method

**Comment by Tokazama** [comment]
@nchisholm if you decide to make a PR for this ping me and I'll try to get a quick review. This should be a fairly simple one.

**Comment by nchisholm** [comment]
@Tokazama: done. Thanks!
