### ISSUE TITLE
how to tell if type has `ldiv!` defined

### ISSUE THREAD

**Issue by vpuri3** [JuliaArrays/ArrayInterface.jl#258]
i might be misinterpreting the objective of this package, but is there a function anywhere that can tell if my matrix operator type has ldiv!  defined?

https://github.com/SciML/LinearSolve.jl/issues/110

**Comment by ChrisRackauckas** [comment]
For this kind of thing there's Tricks.jl and the Julia built-in `isdefined`, so I think it's not necessarily needed in the interface functions?

**Comment by vpuri3** [comment]
thanks for clarifying
