### ISSUE TITLE
Fix CI to run on PR branches

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/ArrayInterface.jl#268]
https://github.com/JuliaArrays/ArrayInterface.jl/pull/266 showed that everything is now fine locally, but CI does not run on the PR branches correctly. Talked with @giordano on this, as I wasn't able to figure it out.

**Comment by Tokazama** [comment]
We have a lot of downstream tests now and I'm consistently encountering failures that I'm pretty sure are unrelated to changes I'm making. Should we specifically be requesting a review from relevant package maintainers to ensure we aren't breaking things. For example, I'm seeing DiffEqSensitivity.jl/Core4/1.6 isn't passing but we haven't been making any changes to functions or traits used in those packages.
