### ISSUE TITLE
Mono repos much more confusing than separate repos

### ISSUE THREAD

**Issue by chriselrod** [JuliaArrays/ArrayInterface.jl#272]
So far, I think it'd be easier to navigate and understand ArrayInterface if everything was in a separate git repo.

E.g., what did version 0.1.0 of ArrayInterfaceOffsetArrays look like, vs what does it look like now?

Using the released version, tests fail:
https://github.com/JuliaSIMD/VectorizationBase.jl/runs/6540991814?check_suite_focus=true
But locally they passed on master.

I can see it was fixed in this commit:
https://github.com/JuliaArrays/ArrayInterface.jl/commit/8ac6d4e7f64583c5d7f4d20ea505220b77f1be11
but where is that commit relative to the release version?

From the fact that the release fails, I can tell that
> [015c0d05] ArrayInterfaceOffsetArrays v0.1.0

was from before that commit.
But, maybe there is also a 0.1.1 release after this commit? How do I check?

Etc.

I think separate repos are easier.

**Comment by chriselrod** [comment]
Seems it did already exist: https://github.com/JuliaArrays/ArrayInterface.jl/issues/10#issuecomment-1133809007

**Comment by chriselrod** [comment]
Seems ArrayInterface 6 restricts it to 0.1.0:
https://github.com/JuliaSIMD/VectorizationBase.jl/runs/6541055845?check_suite_focus=true

**Comment by ChrisRackauckas** [comment]
ArrayInterfaceOffsetArrays.jl needs a version bump to allow 6.

https://github.com/JuliaArrays/ArrayInterface.jl/compare/v6.0.0...master#diff-3d76c60ebb9a40cc3f7d4f22d2d21e7d86aefd9973f6f262032c3babd07ec2c6R11

**Comment by chriselrod** [comment]
This continues to be annoying. In order to see if this change is actually okay, how do I easily look up what changed in ArrayInterfaceOffsetArrays 0.1.2?
https://github.com/JuliaSIMD/LoopVectorization.jl/pull/412#discussion_r893860162
It'd be trivial if ArrayInterfaceOffsetArrays were in its own git repo.

**Comment by ChrisRackauckas** [comment]
Fixed to extension packages, and anything static should go to https://github.com/JuliaArrays/StaticArrayInterface.jl
