### ISSUE TITLE
Mysterious downstream LV error

### ISSUE THREAD

**Issue by Tokazama** [JuliaArrays/ArrayInterface.jl#298]
I'm not sure what causing this error https://github.com/JuliaArrays/ArrayInterface.jl/runs/6742300035?check_suite_focus=true. It occurred following merging of #296, which is weird because all tests passed in that PR.

**Comment by chriselrod** [comment]
Well, those errors are in ArrayInterface methods, so we could add them directly here.

**Comment by Tokazama** [comment]
I'm mostly concerned that the PR didn't catch this. I can start working on a fix for the issue with `StrideIndex`.

**Comment by chriselrod** [comment]
```julia
julia> using ArrayInterface, OffsetArrays

julia> A = OffsetArray(PermutedDimsArray(rand(2,3,4), (3,1,2)), (-1,-1,-1));

julia> ArrayInterface.StrideIndex(A)
ERROR: TypeError: in typeassert, expected Tuple{Int64, Int64, Int64}, got a value of type Nothing
Stacktrace:
 [1] (ArrayInterface.StrideIndex{3, nothing, nothing})(s::Tuple{Int64, Int64, Int64}, o::Tuple{Static.StaticInt{1}, Static.StaticInt{1}, Static.StaticInt{1}})
   @ ArrayInterface ~/.julia/dev/ArrayInterface/src/array_index.jl:12
 [2] (ArrayInterface.StrideIndex{3, nothing, nothing})(a::OffsetArray{Float64, 3, PermutedDimsArray{Float64, 3, (3, 1, 2), (2, 3, 1), Array{Float64, 3}}})
   @ ArrayInterface ~/.julia/dev/ArrayInterface/src/array_index.jl:15
 [3] ArrayInterface.StrideIndex(a::OffsetArray{Float64, 3, PermutedDimsArray{Float64, 3, (3, 1, 2), (2, 3, 1), Array{Float64, 3}}})
   @ ArrayInterface ~/.julia/dev/ArrayInterface/src/array_index.jl:18
 [4] top-level scope
   @ REPL[4]:1

julia> using ArrayInterfaceOffsetArrays

julia> ArrayInterface.StrideIndex(A)
ArrayInterface.StrideIndex{3, (3, 1, 2), 2, Tuple{Int64, Static.StaticInt{1}, Int64}, Tuple{Int64, Int64, Int64}}((6, static(1), 2), (0, 0, 0))
```
https://github.com/JuliaSIMD/VectorizationBase.jl/commit/f1bac4cfb10980cb6dd5441d80c94681087263cd

**Comment by chriselrod** [comment]
Odd that this worked before without ArrayInterfaceOffsetArrays loaded.
FWIW, people are unlikely to encounter this in practice, as LoopVectorization does load `ArrayInterfaceOffsetArrays`: https://github.com/JuliaSIMD/LoopVectorization.jl/blob/cbb9f2324ec3cb2c4aa5523d8c4fb98147aa7855/src/LoopVectorization.jl#L6

**Comment by Tokazama** [comment]
> Odd that this worked before without ArrayInterfaceOffsetArrays loaded.

Yeah, there were a lot of odd errors I found once I removed blindly unwrapping parent arrays. 

>FWIW, people are unlikely to encounter this in practice, as LoopVectorization does load `ArrayInterfaceOffsetArrays`: https://github.com/JuliaSIMD/LoopVectorization.jl/blob/cbb9f2324ec3cb2c4aa5523d8c4fb98147aa7855/src/LoopVectorization.jl#L6

In that case we probably don't have an actual error here that needs to be fixed?

**Comment by chriselrod** [comment]
> In that case we probably don't have an actual error here that needs to be fixed?

Yeah. Downstream tests also pull the latest commit, so I don't need to issue a VB release. Tests should (hopefully) pass next time they run.

**Comment by Tokazama** [comment]
Thanks for checking this out! I was worried about leaving this broken over night.
