### ISSUE TITLE
Bump minimum Julia version to 1.9 as soon as it is released?

### ISSUE THREAD

**Issue by chriselrod** [JuliaArrays/ArrayInterface.jl#372]
I think we should bump the minimum Julia version to 1.9, `mv` all the `lib` packages to `ext`, and make them `[weakdeps]` that get autoloaded.

This would make it easier for LV to drop StaticArrays as a dependency.
LV can't make StaticArrays a weakdep itself, as we'd get
StaticArrays -> StaticArraysExt -> ArrayInterfaceStaticArrays -> StaticArrays -> deadlock error

**Comment by ChrisRackauckas** [comment]
I think we just need to make ArrayInterfaceCore have weak dependencies on everything else?

**Comment by chriselrod** [comment]
And then just place lines like
```julia
if !isdefined(Base, :get_extension)
    using ArrayInterfaceStaticArrays
end
```
in the packages using them (where they currently unconditionally load the sublib)?

Then `ArrayInterfaceStaticArrays` could be both in `[deps]` and `[weakdeps]`?
That should preserve the current behavior, while only loading conditionally in the future (with ArrayInterfaceCore handling the auto-loading of the extension).

**Comment by ChrisRackauckas** [comment]
Yes, and then ArrayInterface would be pulled in with Static? Then everyone just uses ArrayInterfaceCore and it works out.

**Comment by chriselrod** [comment]
Part of the motivation for dropping older Julia versions, however, is that I'm not sure we really want all these `lib` packages to keep existing.

We'd certainly discourage their use in Julia >=1.9, in favor of the extensions.

Note that an extension cannot load one of the `lib` packages, so these packages would have to become the extensions. We can still have `ext/PackageExt/PackageExt.jl`, so we could perhaps still maintain them as packages to keep supporting older Julia's, but I'm not sure what the value proposition of that is.

**Comment by ChrisRackauckas** [comment]
I'd be willing to bump this library to v1.9. It's a pretty specific case that really needs weak dependencies and there really isn't a better answer. It doesn't have a lot of dependencies that would be changing under its feet either, so its v1.6 version should just be "fine" indefinitely.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaArrays/ArrayInterface.jl/pull/373 will keep working on v1.6, but we'll have a breaking update. It'll just use requires on the earlier versions, but whatever.
