### ISSUE TITLE
Two extensions defining the same method; breaks precompilation.

### ISSUE THREAD

**Issue by thomvet** [JuliaArrays/ArrayInterface.jl#385]
I came across the following today when adding DifferentialEquations.jl to an otherwise clean environment on Julia-1.9beta4.

```
OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
│  WARNING: Method definition adapt_storage(Type{var"#s1"} where var"#s1"<:(StaticArraysCore.SArray{S, T, N, L} where L where N where T), Array{T, N} where N where T) where {S} in module ArrayInterfaceStaticArraysCoreExt at C:\Users\thvt\.julia\packages\ArrayInterface\lyyrK\ext\ArrayInterfaceStaticArraysCoreExt.jl:32 overwritten in module AdaptStaticArraysExt at C:\Users\thvt\.julia\packages\Adapt\xviDc\ext\AdaptStaticArraysExt.jl:6.
│    ** incremental compilation may be fatally broken for this module **
```

There are a number of repeats of this when precompiling happens, presumably because, ArrayInterface.jl features in a lot of packages that in turn appear in DifferentialEquations.jl...

Solution is probably to not to be a pirate (AARRR), but just drop this line:
https://github.com/JuliaArrays/ArrayInterface.jl/blob/b606399c4a90c35647dae9ae30ac04259f0fcdbd/ext/ArrayInterfaceStaticArraysCoreExt.jl#L32

It's already taken care of by Adapt.jl, because the extension adapting adapt_storage for staticarrays should already be triggered there?

I may find the time to test that change later today, but in case anyone wants to beat me to it: be my guest!

**Comment by thomvet** [comment]
... Don't know why I overlooked this. The fix already exists.
https://github.com/JuliaArrays/ArrayInterface.jl/pull/380

**Comment by ChrisRackauckas** [comment]
Yes, this just got upstreamed last week and I haven't merged my PR https://github.com/JuliaArrays/ArrayInterface.jl/pull/380 because I've been traveling. But train wifi is good enough to finish this. Sorry about the hiccup but the upstreaming is better in the long run.
