### ISSUE TITLE
can_setindex for <:MArray evaluates to false

### ISSUE THREAD

**Issue by jecs** [JuliaArrays/ArrayInterface.jl#428]
As the title suggests, `can_setindex(::Type{<:StaticArrays.MArray})` evaluates to `false`, even though `setindex!` is defined for `MArray`.

Suggested fix:
```
ArrayInterface.can_setindex(::Type{<:StaticArrays.MArray}) = true
```

**Comment by ChrisRackauckas** [comment]
Yes that should be changed./

**Comment by Tokazama** [comment]
@jecs , this should be a pretty straightforward PR. If you make one I'd be happy to review it (make sure to tag me to get my attention though).
